# Generated by Django 2.1.3 on 2018-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20181119_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagetime',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
