# Generated by Django 2.1.3 on 2018-11-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20181122_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='average_in_time',
        ),
    ]
