# Generated by Django 2.1.3 on 2018-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_remove_employee_average_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='average_in_time',
            field=models.TimeField(null=True),
        ),
    ]
